version: "3"

services:
  pg:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=decidim
      - POSTGRES_DB=decidim_production
    volumes:
      - decidim-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U decidim -d decidim_production"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network
    restart: unless-stopped

  decidim:
    build: .
    working_dir: /app
    # On utilise simplement 0.0.0.0:3000 sans préciser tcp:// qui peut parfois troubler Traefik
    command: sh -c "sleep 15 && bundle exec rake db:migrate && bundle exec puma -b tcp://0.0.0.0:3000"
    volumes:
      - decidim-uploads:/app/public/uploads
      - decidim-storage:/app/storage
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://decidim:${DATABASE_PASSWORD}@pg:5432/decidim_production
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=decidim
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=decidim_production
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - DISABLE_FORCE_SSL=true
      - DECIDIM_FORCE_SSL=false 
      - QUEUE_ADAPTER=async
      - PORT=3000
      - DECIDIM_SERVER_URL=https://ceci-et-cela.space
      - RAILS_MAX_THREADS=5

    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - dokploy-network
    restart: unless-stopped

volumes:
  decidim-pg-data:
  decidim-uploads:
  decidim-storage:

networks:
  dokploy-network:
    external: true
    name: dokploy-network
