source "https://rubygems.org"

ruby "3.2.2" # Version Ruby recommandée pour Decidim

gem "decidim", "~> 0.28.0" # Le coeur de Decidim
gem "decidim-conferences", "~> 0.28.0"
gem "decidim-consultations", "~> 0.28.0"
gem "decidim-initiatives", "~> 0.28.0"
gem "decidim-templates", "~> 0.28.0"

gem "bootsnap", "~> 1.4", require: false
gem "puma", ">= 6.3.1"
gem "uglifier", "~> 4.1"
gem "delayed_job_active_record" # Pour les emails asynchrones
gem "net-smtp", require: false
