default: &default
  decidim:
    application_name: <%= ENV.fetch("DECIDIM_NAME", "Decidim") %>
    mailer_sender: <%= ENV.fetch("DECIDIM_MAILER_SENDER", "noreply@" + ENV.fetch("DECIDIM_HOST", "localhost")) %>
    available_locales: <%= ENV.fetch("DECIDIM_AVAILABLE_LOCALES", "fr") %>
    default_locale: <%= ENV.fetch("DECIDIM_DEFAULT_LOCALE", "fr") %>
    currency_unit: "€"
    maximum_attachment_size: 10
    maximum_avatar_size: 5
    maximum_logo_size: 2
    reference_prefix: <%= ENV.fetch("DECIDIM_REFERENCE_PREFIX", "DEC") %>

development:
  <<: *default
  secret_key_base: insecure-secret-key-base-just-for-development

test:
  <<: *default
  secret_key_base: insecure-secret-key-base-just-for-tests

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
